FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:0.7.3 /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml ./
RUN uv sync --no-dev --no-install-project

COPY README.md ./
COPY src ./src
RUN uv sync --no-dev

CMD ["uv", "run", "python", "-m", "masterclass_mlops.model_service.app"]
