events {}

http {
  limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/m;

  upstream gateway_upstream {
    server gateway:8000;
  }

  server {
    listen 8080;

    location /nginx_status {
      stub_status;
      allow 127.0.0.1;
      allow 172.16.0.0/12;
      allow 10.0.0.0/8;
      deny all;
    }

    location /health {
      proxy_pass http://gateway_upstream/health;
    }

    location /auth/ {
      limit_req zone=api_limit burst=5 nodelay;
      proxy_pass http://gateway_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
      limit_req zone=api_limit burst=5 nodelay;
      proxy_pass http://gateway_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
