events {}

http {
  log_format json_combined escape=json
    '{'
      '"timestamp":"$time_iso8601",'
      '"service":"nginx",'
      '"remote_addr":"$remote_addr",'
      '"request_method":"$request_method",'
      '"request_uri":"$request_uri",'
      '"status":$status,'
      '"request_time":$request_time,'
      '"bytes_sent":$bytes_sent,'
      '"request_id":"$request_id"'
    '}';

  access_log /var/log/nginx/access.log json_combined;
  error_log /var/log/nginx/error.log warn;
  limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/m;

  upstream gateway_upstream {
    server gateway:8000;
  }

  server {
    listen 8080;

    location /nginx_status {
      stub_status;
      allow all;
    }

    location /health {
      proxy_pass http://gateway_upstream/health;
    }

    location /auth/ {
      limit_req zone=api_limit burst=5 nodelay;
      proxy_pass http://gateway_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
      limit_req zone=api_limit burst=5 nodelay;
      proxy_pass http://gateway_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
